  name: Build and Deploy to Cloud Run
  on:
    push:
      branches:
        - main
  jobs:
    build-push-gcr:
      uses: amit-patil/ci-cd-deployment-workflows/.github/workflows/reusable-java-workflow.yaml@main
      with:
        repository-name: amit-patil/hello-world
        ref: main
       
     

