  name: Build and Deploy to Cloud Run
  on:
    push:
      branches:
        - main
  env:
    IMAGE_NAME: java-helloworld
    PROJECT_ID: banktestproject-398809
    ARTIFACTORY_IMAGE_TAG: ${{github.run_number}}
  jobs:
    build-push-gcr:
      name: Build and Push to GCP
      runs-on: ubuntu-latest  
      permissions:
        contents: 'read'
        id-token: 'write'
      steps:
        - name: repo-checkout
          uses: actions/checkout@v3
 

        - name: 'Authenticate to Google Cloud'
          id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            token_format: 'access_token'
            workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
            service_account: '${{ secrets.SA_EMAIL }}' 
     
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Run the Maven verify phase
          run: mvn --batch-mode --update-snapshots verify

        - name: Build Docker Image
          run: docker build -t $IMAGE_NAME:latest .

        - name: Configure Docker Client
          run: |-
            gcloud auth configure-docker --quiet
            gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

        - name: Push Docker Image to Container Registry (GCR)
          run: |-
            docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest 
            docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$ARTIFACTORY_IMAGE_TAG
            docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
            docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$ARTIFACTORY_IMAGE_TAG
        
        - name: Push Docker Image to Artifact Registry
          run: |-
            docker tag $IMAGE_NAME:latest europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$ARTIFACTORY_IMAGE_TAG
            docker push europe-west3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$ARTIFACTORY_IMAGE_TAG

        - name: Deploy to Cloud run
          run: |-
            gcloud run deploy java-helloworld --region=europe-west3 --image=gcr.io/$PROJECT_ID/$IMAGE_NAME:latest




     

